spring.application.name=rescue-system
spring.datasource.url=jdbc:mysql://localhost:3306/rescue_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Akalya@07

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect